services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: payroll
      POSTGRES_USER: wave
      POSTGRES_PASSWORD: payroll123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wave -d payroll" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
