"""First migration

Revision ID: 30c11349ee44
Revises: 
Create Date: 2025-03-02 07:26:13.107807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c11349ee44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_group',
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.Column('wages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_group_id')
    )
    op.create_table('time_report',
    sa.Column('time_report_id', sa.Integer(), nullable=False),
    sa.Column('date_uploaded', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('time_report_id')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_group.job_group_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('time_entry',
    sa.Column('time_entry_id', sa.String(), nullable=False),
    sa.Column('time_report_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.Column('date_worked', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_group.job_group_id'], ),
    sa.ForeignKeyConstraint(['time_report_id'], ['time_report.time_report_id'], ),
    sa.PrimaryKeyConstraint('time_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entry')
    op.drop_table('employee')
    op.drop_table('time_report')
    op.drop_table('job_group')
    # ### end Alembic commands ###
