"""First migration

Revision ID: acf99f129e94
Revises: 
Create Date: 2025-02-27 09:36:01.810955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf99f129e94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_group',
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.Column('wages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_group_id')
    )
    op.create_table('time_report',
    sa.Column('time_report_id', sa.Integer(), nullable=False),
    sa.Column('date_uploaded', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('time_report_id')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_group.job_group_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('time_entry',
    sa.Column('time_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_report_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('job_group_id', sa.String(length=2), nullable=False),
    sa.Column('date_worked', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['job_group_id'], ['job_group.job_group_id'], ),
    sa.ForeignKeyConstraint(['time_report_id'], ['time_report.time_report_id'], ),
    sa.PrimaryKeyConstraint('time_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entry')
    op.drop_table('employee')
    op.drop_table('time_report')
    op.drop_table('job_group')
    # ### end Alembic commands ###
